server:
  port: 9997

spring:
  datasource:
    url: jdbc:mysql://localhost/sys-log?serverTimezone=UTC&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 117881
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #消息确认
    publisher-confirms: true
    #虚拟主机
    virtual-host: /

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
