spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
      label: master
  profiles:
    active: native
  application:
    name: config-server

# port
server:
  port: 8769

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
